[theme]
primaryColor = "#41a2be"
backgroundColor = "#191818"
secondaryBackgroundColor = "#d6ebf1"
textColor = "#ffffff"
font = "monospace"

[server]
port = 8502
enableStaticServing = true

[browser]
gatherUsageStats = false
