[theme]
primaryColor = "#ffffff"
backgroundColor = "#191818"
secondaryBackgroundColor = "#080808"
textColor = "#ffffff"
font = "monospace"

[server]
port = 4444
enableStaticServing = true

[browser]
gatherUsageStats = false
